name: CLIENT Change Detection

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Ensures the repository is checked out

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./client  # the directory where your Dockerfile is located
          file: ./client/Dockerfile  # Explicit path to the Dockerfile
          push: true
          tags: |
            nouranahmed5/client:${{ github.run_number }}  
            nouranahmed5/client:latest   